// Declare the game state enum:
enum GAME_STATE
{
	GAME_STATE_MENU,
	GAME_STATE_PLAY,
	GAME_STATE_PAUSE,
	GAME_STATE_DEATH,
};

// Declare the player state enum:
enum PLAYER_STATE
{
	PLAYER_STATE_NORMAL,
	PLAYER_STATE_PICKAXE,
	PLAYER_STATE_AXE,
	PLAYER_STATE_WATERING,
	PLAYER_STATE_HOE,
	PLAYER_STATE_FISHING,
};

// Declare the item type enum:
enum ITEM_TYPE
{
	// Tools:
	ITEM_TYPE_WATERING_CAN=1,
	ITEM_TYPE_SWORD,
	ITEM_TYPE_PICKAXE,
	ITEM_TYPE_AXE,
	ITEM_TYPE_HOE,
	ITEM_TYPE_FISHING_ROD,
	
	// Seeds:
	ITEM_TYPE_SEEDS,
	
	// Crops:
	ITEM_TYPE_CROPS,
};

// Declare the seasons enum:
enum SEASONS
{
	SPRING,
	SUMMER,
	AUTUMN,
	WINTER,
};

// Declare the crop type enum:
enum CROP_TYPE
{
	CROP_TYPE_CARROT=1,
	CROP_TYPE_TOMATO,
	CROP_TYPE_STRAWBERRY,
	CROP_TYPE_PUMPKIN,
	CROP_TYPE_CORN,
	CROP_TYPE_POTATO,
	CROP_TYPE_WATERMELON,
	CROP_TYPE_RADISH,
	CROP_TYPE_LETTUCE,
	CROP_TYPE_WHEAT,
	CROP_TYPE_EGGPLANT,
}
